pub mod ports;
pub mod use_cases;

pub use ports::{
    EventPublisher, InstrumentRepository, OrderBookRepository, RateLimitConfig, RateLimitResult,
    RateLimitStatus, RateLimiter,
};
pub use use_cases::{
    // Withdrawal management
    AddConfirmationCommand,
    // DEX / AMM
    AddLiquidityCommand,
    AddLiquidityExecutionResult,
    // Order management
    CancelError,
    CancelOrderCommand,
    CancelOrderResult,
    CancelOrderUseCase,
    ConfirmWithdrawalCommand,
    // Deposit management
    Deposit,
    DepositCreditedEvent,
    DepositId,
    DepositStatus,
    DepthError,
    DepthResult,
    ExchangeInfo,
    ExchangeInfoError,
    FailWithdrawalCommand,
    GetDepthQuery,
    GetDepthUseCase,
    GetExchangeInfoUseCase,
    LiquidityAddedEvent,
    LiquidityRemovedEvent,
    LiquidityUseCase,
    LiquidityUseCaseError,
    OrderError,
    ProcessDepositError,
    ProcessDepositUseCase,
    ProcessDepositsResult,
    ProcessWithdrawalCommand,
    ProcessWithdrawalError,
    ProcessWithdrawalResult,
    ProcessWithdrawalUseCase,
    RegisterDepositAddressCommand,
    RemoveLiquidityCommand,
    RemoveLiquidityExecutionResult,
    RequestWithdrawalCommand,
    RequestWithdrawalResult,
    RequestWithdrawalUseCase,
    SubmitOrderCommand,
    SubmitOrderResult,
    SubmitOrderUseCase,
    SwapCommand,
    SwapExecutedEvent,
    SwapExecutionResult,
    SwapQuote,
    SwapUseCase,
    SwapUseCaseError,
    WithdrawalUseCaseError,
};
